### ISSUE TITLE
Text in "about" confused because of the old reference

### ISSUE THREAD

**Issue by Foxdelmar** [subliun/Antox#148]
Under Antox/app/src/main/res/values-de/strings.xml
in line 
 <string name="license2">Quellcode vorhanden unter\nhttps://github.com/Astonex/Antox</string>
please correct it to https://github.com/subliun/Antox

I downloaded the app with the repo https://antox.me/fdroid/repo within f-droid and was not sure where the actual code is edited on github. So please update the github URL in all languages.

Once again: How can I support you? More testing? Donations? Advertisement?

**Comment by subliun** [comment]
Hey, thanks very much for the issue reports. If you're not an Android dev, translations are always needed. Otherwise the best way to help is keep testing and report absolutely every issue you find, exactly as you've been doing. :)

I'm not currently accepting donations, though I might set up a patreon at some point.

**Comment by Foxdelmar** [comment]
so I keep on testing, as long as you are developing. ;)
Will wait for any opportunities to donate!

**Comment by aaannndddyyy** [comment]
Do you use the trnaslations that you have on transifex?
They are regularly updated.

**Comment by 00firestar00** [comment]
might be better to separate that out from the strings and put the URL in its own string value, that way if it does change it won't have to be changed in every language file
perhaps just: `<string name="github_repo">https://github.com/subliun/Antox</string>`
