### ISSUE TITLE
File transfers turn into messages when they fail sometimes

### ISSUE THREAD

**Issue by subliun** [subliun/Antox#173]

**Comment by agilob** [comment]
It happens 10/10 when sending a sceenshot from qtox to antox.

**Comment by subliun** [comment]
Even when the transfer succeeded? I'm pretty sure this is a bug I introduced when I simplified message types in the db, that of something to do with the new messgage holders. Either way I'll sort it out.

**Comment by agilob** [comment]
Ym.. it never succeeded for me, transfer was automatically changed to message.

1. send screenshot from qtox
2. several seconds of waiting for acceptance in qtox
3. qtox: transfer rejected
4. antox: new message

**Comment by MuSamDu** [comment]
yeah same here! i'm transfering images from antox to another antox and never succeed!!

**Comment by MuSamDu** [comment]
@subliun It's a BUG man! Do you think you can fix it? Now the only thing i got with antox is pure-text messaging. No file transfers, no images displayed. only filenames instead!

**Comment by subliun** [comment]
I could never reproduce #101 but I think I've fixed this.

**Comment by 00firestar00** [comment]
Broken for me after commit ef4f26bcc79085a953a49d561fa3e76256573165 So I think it has something to do with the message type changes in DB. Had one phone run the code on master while I checked out that particular commit for another phone. The file transfers are also coming in as though you sent them rather than your friend. Seems the check on line 95 of ChatMessageAdapter is incorrect. It's passing through with `msg.isMine` instead of failing and showing you the accept/reject prompt
```
if (msg.isMine) {
  fileHolder.setProgressText(R.string.file_request_sent)
} else {
  fileHolder.showFileButtons()
}
```

**Comment by subliun** [comment]
Yeah I've fixed it locally. Silly mistake. I'm just going to make some changes to prevent it happening again.
