### ISSUE TITLE
download dependecis script does not complete

### ISSUE THREAD

**Issue by freelabcc** [subliun/Antox#231]
it seems there is something broken in the download dependencies script

./download-dependencies.sh

protobuf dependency will not be found

https://build.tox.chat/job/protobuf_build_android_armel_release/lastSuccessfulBuild/artifact/protobuf.jar', 'app\libs\protobuf-java-2.6.1.jar'

**Comment by freelabcc** [comment]
it seems android studio is able to find the dependency by itself

**Comment by wiiam** [comment]
This is due to the [latest build for protobuf](https://build.tox.chat/job/protobuf_build_android_armel_release/) not outputting a jar file

At this time Antox does not use the protobuf library so you can remove
```
DEL /F /Q app\libs\protobuf-java-2.6.1.jar
echo "Removed old version: protobuf-java-2.6.1.jar"
echo "Downloading latest version: protobuf-java-2.6.1.jar"
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://build.tox.chat/job/protobuf_build_android_armel_release/lastSuccessfulBuild/artifact/protobuf.jar', 'app\libs\protobuf-java-2.6.1.jar')"
```
from the batch file or
```
rm app/libs/protobuf-java-2.6.1.jar
wget https://build.tox.chat/job/protobuf_build_android_armel_release/lastSuccessfulBuild/artifact/protobuf.jar -O app/libs/protobuf-java-2.6.1.jar
```
from the shell script file, depending on what OS you are using, and Antox will still build fine.

**Comment by subliun** [comment]
@wiiam would you fix this?
