### ISSUE TITLE
[Regression] Copying received text doesn't work on 0.22

### ISSUE THREAD

**Issue by zetok** [subliun/Antox#42]
Text in question:
```
p-ping?
```

I've held my finger on received message for some time, with no visible effect.

**Comment by SelfDestruct68** [comment]
Try yap and hold your finger more on the upper side of the message. Like the edge and a option menu will popup

**Comment by ericthefish** [comment]
There are two ways to open a thread, either by tapping a thread on the chat pane (left tab) or by tapping a contact name on the contacts pane (right tab).  I find that if I can't copy text from a chat (long press has no effect at all), opening the same thread using the other method allows me to copy text after long pressing a message.

I know that sounds weird, but that seems to be what I'm seeing.  Hope that helps rather than making things more confusing.

**Comment by Doom032** [comment]
Sometimes I notice I can't copy a text from a message and then I select the input text box and then try to longpress the message and it seems to work. Though one time I noticed that didn't work, and the text in question was a link, after ending the longpress it'd always just open the link. Might be 2 separate issues?

**Comment by v6** [comment]
// , Anybody test this?
